### List all users
GET http://localhost:6435/admin-api/users


### View a specific user's posts
GET http://localhost:6435/admin-api/users/{{adminTarget}}/posts


### Block a user  (sets isBlocked: true)
PATCH http://localhost:6435/admin-api/users/{{adminTarget}}/block


### Unblock a user  (sets isBlocked: false)
PATCH http://localhost:6435/admin-api/users/{{adminTarget}}/unblock
