### Create a text-only post
POST http://localhost:6435/post-api/createpost
Content-Type: application/json

{
  "description": " This is my first post."
}


### Create a post with an image
POST http://localhost:6435/post-api/createpost
Content-Type: application/json

{
  "description": "Check out this photo!",
  "mediaUrl": "https://res.cloudinary.com/duplxxfmm/image/upload/v1778048823/cld-sample-2_fvkryv.jpg",
  "mediaType": "image"
}


### Create a post with a video
POST http://localhost:6435/post-api/createpost
Content-Type: application/json

{
  "description": "Watch this clip.",
  "mediaUrl": "https://res.cloudinary.com/demo/video/upload/sample.mp4",
  "mediaType": "video"
}


### Get home feed
GET http://localhost:6435/post-api/feed

###

### View a single post
GET http://localhost:6435/post-api/viewpost/69fae028cbb2ab5d3d706eaa

###

### Soft-delete a post
PUT http://localhost:6435/post-api/delpost/69fae028cbb2ab5d3d706eaa

###

### Like a post
PUT http://localhost:6435/post-api/likepost/69fae028cbb2ab5d3d706eaa

###

### Unlike a post
PUT http://localhost:6435/post-api/unlikepost/69fae028cbb2ab5d3d706eaa

###

### Add a comment
POST http://localhost:6435/post-api/comment/69fae028cbb2ab5d3d706eaa
Content-Type: application/json

{
  "comment": "Great post! Really enjoyed reading this.",
  "username": "lokeshwar873"
}

###

### Delete a comment
PUT http://localhost:6435/post-api/delcomment/69fae131cbb2ab5d3d706eac

{
  "pid": "69fae028cbb2ab5d3d706eaa"
}

