### 1. Register
POST http://localhost:6435/auth/register
Content-Type: application/json

{
  "firstName": "Suman",
  "lastName": "Mondal",
  "username": "sumanmondal02",
  "email": "suman@mail.com",
  "password": "@123456",
  "gender": "male",
  "dob": "2005-12-02"
}

###

### 2. Login
POST http://localhost:6435/auth/login
Content-Type: application/json

{
  "email": "suman@mail.com",
  "password": "@123456"
}

###

### 3. Logout
POST http://localhost:6435/auth/logout


### View own profile
GET http://localhost:6435/user-api/self



### Update own profile
PUT http://localhost:6435/user-api/updateProfile
Content-Type: application/json

{
  "username": "lokeshwar",
  "email": "lokeshwar@mail.com",
  "bio": "Full stack dev | MERN",
  "firstName": "Lokesh",
  "lastName": "Maddula"
}



### Deactivate own account
PUT http://localhost:6435/user-api/deactivate

### Activate own account
PUT http://localhost:6435/user-api/activate/69fad27fd0981e81c8238806



### Follow a user
POST http://localhost:6435/user-api/follow/69fad418f411035457b851df


### Unfollow a user
POST http://localhost:6435/user-api/unfollow/69fad418f411035457b851df


### Get own followers list
GET http://localhost:6435/user-api/followerslist



### Get own following list
GET http://localhost:6435/user-api/followinglist



### Search users by username or name
GET http://localhost:6435/user-api/search/sumanmondal02



###  Get another user's public profile
GET http://localhost:6435/user-api/profile/69fad418f411035457b851df


###  Get notifications
GET http://localhost:6435/user-api/notifications


###  Mark a notification as read
PATCH http://localhost:6435/user-api/notifications/69fadad0404484efff6c5823/read
